import fs from "fs";
import path from "path";
import { spawn, execSync } from "child_process";

export interface BenchmarkConfig {
  sourceCodePath: string;       // Path to Java source code
  warmupIterations: number;
  measurementIterations: number;
  javaPath?: string;
  mavenPath?: string;
}

export async function runAutoBenchmarks(
  staticReports: any[],
  outputDir: string,
  sourceCodePath: string,
  config: Partial<BenchmarkConfig> = {}
): Promise<string> {
  console.log("🚀 Starting automatic benchmark generation...");
  console.log(`📁 Source code path: ${sourceCodePath}`);
  
  if (!fs.existsSync(sourceCodePath)) {
    throw new Error(`Source code directory not found: ${sourceCodePath}`);
  }
  
  // Extract methods from static reports
  const methods = extractMethodsFromReports(staticReports);
  console.log(`📊 Found ${methods.length} methods for benchmarking`);
  
  if (methods.length === 0) {
    throw new Error("No methods found for benchmarking");
  }
  
  // Check if Java and Maven are available
  checkJavaAndMaven();
  
  // Create benchmark project directory
  const benchmarkDir = path.join(outputDir, "benchmark-project");
  fs.mkdirSync(benchmarkDir, { recursive: true });
  
  // Step 1: Copy source code to benchmark project
  console.log("📦 Copying source code...");
  copySourceCode(sourceCodePath, benchmarkDir);
  
  // Step 2: Generate benchmark classes
  console.log("⚙️  Generating benchmark classes...");
  await generateBenchmarkClasses(methods, benchmarkDir, sourceCodePath);
  
  // Step 3: Create Maven project
  console.log("📋 Creating Maven project...");
  createMavenProject(benchmarkDir);
  
  // Step 4: Compile and run benchmarks
  console.log("🔨 Compiling project...");
  await compileProject(benchmarkDir);
  
  console.log("🏃 Running benchmarks...");
  const resultsPath = await runBenchmarks(benchmarkDir, config);
  
  console.log(`✅ Benchmarks completed. Results saved to: ${resultsPath}`);
  return resultsPath;
}

function checkJavaAndMaven(): void {
  try {
    execSync("java -version", { stdio: 'pipe' });
    console.log("✅ Java is available");
  } catch (error) {
    throw new Error("Java is not installed or not in PATH");
  }
  
  try {
    execSync("mvn --version", { stdio: 'pipe' });
    console.log("✅ Maven is available");
  } catch (error) {
    throw new Error("Maven is not installed or not in PATH");
  }
}

function copySourceCode(sourcePath: string, destPath: string): void {
  const srcDir = path.join(destPath, "src", "main", "java");
  fs.mkdirSync(srcDir, { recursive: true });
  
  // Copy all Java files
  const copyFiles = (src: string, dest: string) => {
    const entries = fs.readdirSync(src, { withFileTypes: true });
    
    for (const entry of entries) {
      const srcPath = path.join(src, entry.name);
      const destPath = path.join(dest, entry.name);
      
      if (entry.isDirectory()) {
        fs.mkdirSync(destPath, { recursive: true });
        copyFiles(srcPath, destPath);
      } else if (entry.name.endsWith('.java')) {
        fs.copyFileSync(srcPath, destPath);
      }
    }
  };
  
  copyFiles(sourcePath, srcDir);
  console.log(`✅ Copied Java source files`);
}

async function generateBenchmarkClasses(
  methods: any[], 
  benchmarkDir: string, 
  sourceCodePath: string
): Promise<void> {
  const { generateJMHBenchmarkClass, generateCustomBenchmarkRunner } = require("../generators/jmhBenchmarkGenerator");
  
  const packageName = "com.greencode.benchmarks";
  const srcDir = path.join(benchmarkDir, "src", "main", "java");
  
  // Generate JMH benchmark class
  const jmhCode = generateJMHBenchmarkClass(methods, packageName);
  const jmhFile = path.join(srcDir, ...packageName.split('.'), "AutoGeneratedBenchmark.java");
  fs.writeFileSync(jmhFile, jmhCode);
  
  // Generate custom runner
  const customCode = generateCustomBenchmarkRunner(methods, packageName);
  const customFile = path.join(srcDir, ...packageName.split('.'), "CustomBenchmarkRunner.java");
  fs.writeFileSync(customFile, customCode);
  
  console.log(`✅ Generated benchmark classes`);
}

function createMavenProject(benchmarkDir: string): void {
  const { generateMavenPom } = require("../generators/jmhBenchmarkGenerator");
  
  const pomXml = generateMavenPom("com.greencode.benchmarks");
  const pomFile = path.join(benchmarkDir, "pom.xml");
  fs.writeFileSync(pomFile, pomXml);
  
  // Create a simple README
  const readme = `# Auto-Generated Benchmark Project

This project was automatically generated by GreenCode Energy Analyzer.

## Running Benchmarks

\`\`\`bash
# Build the project
mvn clean package

# Run custom benchmark runner (outputs JSON)
java -cp target/benchmarks.jar com.greencode.benchmarks.CustomBenchmarkRunner

# Results will be saved to: benchmark-results.json
\`\`\`

## JMH Benchmarks

You can also run JMH benchmarks:

\`\`\`bash
java -jar target/benchmarks.jar
\`\`\`
`;
  
  const readmeFile = path.join(benchmarkDir, "README.md");
  fs.writeFileSync(readmeFile, readme);
}

async function compileProject(benchmarkDir: string): Promise<void> {
  return new Promise((resolve, reject) => {
    const mvn = spawn("mvn", ["clean", "compile", "-q"], {
      cwd: benchmarkDir,
      stdio: "inherit"
    });
    
    mvn.on("close", (code) => {
      if (code === 0) {
        console.log("✅ Project compiled successfully");
        resolve();
      } else {
        reject(new Error(`Maven compilation failed with code ${code}`));
      }
    });
    
    mvn.on("error", reject);
  });
}

async function runBenchmarks(
  benchmarkDir: string, 
  config: Partial<BenchmarkConfig>
): Promise<string> {
  return new Promise((resolve, reject) => {
    const resultsPath = path.join(benchmarkDir, "benchmark-results.json");
    
    const javaArgs = [
      "-cp", "target/benchmarks.jar",
      "com.greencode.benchmarks.CustomBenchmarkRunner"
    ];
    
    const benchmarkProc = spawn("java", javaArgs, {
      cwd: benchmarkDir,
      stdio: "inherit"
    });
    
    benchmarkProc.on("close", (code) => {
      if (code === 0) {
        if (fs.existsSync(resultsPath)) {
          // Copy results to parent directory
          const finalResultsPath = path.join(benchmarkDir, "..", "benchmark-results.json");
          fs.copyFileSync(resultsPath, finalResultsPath);
          resolve(finalResultsPath);
        } else {
          reject(new Error("Benchmark results file not generated"));
        }
      } else {
        reject(new Error(`Benchmark execution failed with code ${code}`));
      }
    });
    
    benchmarkProc.on("error", reject);
  });
}

// Helper function to extract methods
function extractMethodsFromReports(reports: any[]): any[] {
  return reports.map(report => ({
    className: report.className,
    methodName: report.methodName,
    parameters: [],  // You might need to extract these from AST
    returnType: "void",
    isStatic: false
  }));
}

// Fallback function for mock benchmarks
export function generateMockBenchmarks(
  staticReports: any[], 
  outputDir: string
): string {
  const mockResults = staticReports.map(report => {
    const baseTime = report.loopCount * 5 + report.nestingDepth * 2 + report.conditionalsCount;
    const medianMs = Math.max(1, baseTime * 2 + Math.random() * 20);
    
    return {
      className: report.className,
      methodName: report.methodName,
      medianMs: parseFloat(medianMs.toFixed(2)),
      meanMs: parseFloat((medianMs * 1.08).toFixed(2)),
      p95Ms: parseFloat((medianMs * 1.25).toFixed(2)),
      minMs: parseFloat((medianMs * 0.75).toFixed(2)),
      maxMs: parseFloat((medianMs * 1.4).toFixed(2)),
      stdDev: parseFloat((medianMs * 0.12).toFixed(2)),
      runs: 100,
      benchmarkTool: "mock"
    };
  });
  
  const resultsPath = path.join(outputDir, "benchmark-results-mock.json");
  fs.writeFileSync(resultsPath, JSON.stringify(mockResults, null, 2));
  return resultsPath;
}